name: Codecov Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src
      - name: Run Jest tests with coverage
        run: npm test || npm test -- -u
        working-directory: src

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: AsifAliKhan2001/Minicap
          fail_ci_if_error: true
          files: src/coverage/lcov.info # Ensure Jest outputs an `lcov.info` file
          flags: unittests # Optional: Use flags to track unit tests separately
          verbose: true # Enable verbose logging to debug issues
