name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: my-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src
      - name: Build project
        run: npm run build --if-present
        working-directory: src

      - name: Run tests
        run: npm test
        working-directory: src
