name: Run Maestro Test with Recording and Artifact Upload

on:
  push: {}             # Trigger on every push
  workflow_dispatch: {}  # Also allow manual triggering

jobs:
  run-maestro:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install the latest Maestro CLI.
      - name: Install Maestro CLI
        run: |
          curl -L https://github.com/mobile-dev-inc/maestro/releases/latest/download/maestro-linux-amd64.tar.gz -o maestro.tar.gz
          tar -xzf maestro.tar.gz
          sudo mv maestro /usr/local/bin/maestro
          maestro --version

      # Step 3: Run your Maestro test file with recording.
      - name: Run Maestro Test with Recording
        id: run_test
        run: |
          # Execute Maestro in record mode and capture its output.
          OUTPUT=$(maestro record src/app/maestro/test.yaml \
            --apk src/android/app/build/outputs/apk/debug/app-debug.apk \
            --app-id com.anonymous.src \
            --record)
          echo "$OUTPUT"
          # Extract the signed URL (assuming it starts with "https://")
          RECORDING_URL=$(echo "$OUTPUT" | grep -Eo 'https://[^ ]+')
          echo "Recording URL: $RECORDING_URL"
          # Save the URL to a file for later use.
          echo "$RECORDING_URL" > recording_url.txt

      # Step 4: Download the recording file from the signed URL.
      - name: Download Maestro Recording
        run: |
          RECORDING_URL=$(cat recording_url.txt)
          echo "Downloading recording from $RECORDING_URL"
          # Optionally, append a timestamp to the file name to avoid name collisions.
          TIMESTAMP=$(date +%s)
          curl -L "$RECORDING_URL" -o recording-${TIMESTAMP}.mp4
          # Save the filename for later artifact upload.
          echo "recording-${TIMESTAMP}.mp4" > recording_file.txt

      # Step 5: Upload the recording file as an artifact.
      - name: Upload Maestro Recording Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maestro-recording
          path: $(cat recording_file.txt)
